### ISSUE TITLE
[bug] Typo in README.md

### ISSUE THREAD

**Issue by arihantbansal** [m1guelpf/auto-subtitle#2]
In the README.md file, the installation link is incorrect. 

![image](https://user-images.githubusercontent.com/17180950/192756153-2ef973c6-5b60-40c0-b04d-bbb5020f207b.png)

It should be `pip install git+https://github.com/m1guelpf/auto-subtitle.git`. 

Incorret underscore.

**Comment by m1guelpf** [comment]
Fixed by #1
