### ISSUE TITLE
Mention payment in Readme.md

### ISSUE THREAD

**Issue by binarykitchen** [m1guelpf/auto-subtitle#20]
Nice tool. Almost want to use it for www.videomail.io to support Deaf people.

Unfortunately, it uses the [OpenAI's Whisper](https://openai.com/blog/whisper) API which is a paid model. I think it should be mentioned to avoid disappointment and for transparency. Thanks.

**Comment by binarykitchen** [comment]
Oh? What you just said isn't mentioned at https://openai.com/api/pricing/

**Comment by Suleman-Elahi** [comment]
They are not providing Whisper as API. They have open-sourced Whisper that you can download and use offline

https://github.com/openai/whisper

**Comment by binarykitchen** [comment]
Ah yes, sorry. Think I will give it a try for Deaf people for www.videomail.io ...
