### ISSUE TITLE
[Question] How to Make it use GPU

### ISSUE THREAD

**Issue by Suleman-Elahi** [m1guelpf/auto-subtitle#22]
I tried it on my Windows 11 PC and it works perfectly. Then I noticed that every time it uses CPU and hence takes longer time.

![image](https://user-images.githubusercontent.com/24384996/210703291-190279cc-c675-4262-a76f-cfad43f449cb.png)

Is there a way maybe a CLI argument to make it GPU instead for the processing.

**Comment by Suleman-Elahi** [comment]
Got it. Turns out my GPU is not supported.

**Comment by RidePig** [comment]
So is there a way to use GPU instead of CPU?

**Comment by Suleman-Elahi** [comment]
> So is there a way to use GPU instead of CPU? @Suleman-Elahi

If your GPU is supported, then it will automatically use GPU. What GPU you are using ?

**Comment by RidePig** [comment]
> > So is there a way to use GPU instead of CPU? @Suleman-Elahi
> 
> If your GPU is supported, then it will automatically use GPU. What GPU you are using ?

My GPU is NVIDIA GeForce RTX 3050 Laptop GPU.
And could you please tell me how to figure out whether a GPU is supported or not?

**Comment by Suleman-Elahi** [comment]
Yours is definitely supported. It just needs to have CUDA version more than 3.7 I guess. So, you just need to install latest CUDA from Nvidia website : https://developer.nvidia.com/cuda-downloads

**Comment by RidePig** [comment]
@Suleman-Elahi Thank you for your help! I've successfully make the program to use GPU. The reason why I can't use GPU at first is that I'm using wsl1 which dosen't support to use GPU (please refer to [Frequently Asked Questions about Windows Subsystem for Linux](url)). Thank you again for your patience!

**Comment by Minjuiced** [comment]
How did you find out your GPU was not supported? I'm using an RTX 2060 and it only uses my CPU...

**Comment by Fr0zka** [comment]
> Yours is definitely supported. It just needs to have CUDA version more than 3.7 I guess. So, you just need to install latest CUDA from Nvidia website : https://developer.nvidia.com/cuda-downloads
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/a077f383e01baed22bccfb48cc570d3dfaabc06666a666b241b3743788118153/68747470733a2f2f646576656c6f7065722d626c6f67732e6e76696469612e636f6d2f77702d636f6e74656e742f75706c6f6164732f323032322f30342f637564612d696d6167652d313678392d312e6a7067">NVIDIA Developer**[CUDA Toolkit 11.7 Downloads](https://developer.nvidia.com/cuda-downloads)**Get the latest feature updates to NVIDIA's proprietary compute stack.


same as MinJuiced, i just installed cuda, checked for the version and all, using powershell or basic cmd result in the same thing, it doesn't run on GPU (3070) maybe any hint ?
