### ISSUE TITLE
auto-subtitle: command not found

### ISSUE THREAD

**Issue by iftsv** [m1guelpf/auto-subtitle#43]
Hello,
I try to install auto-subtitle according to README.md manual but faced with the issue. There was no any error during installation. 
When I run auto-subtitle, I get error "auto-subtitle: command not found", I try to import auto-subtitle to Python script, get the error as well.
"pip list" shows that auto-subtitle was installed. I've tried two version of Python, on my PC (3.10.6) and using Google Colab (3.9.16)

Please, help me to understand how to use auto-subtitle. Thanks in advance.

**Comment by iftsv** [comment]
Any? :)

**Comment by levfo** [comment]
You have to add the path of the install to your Path environment variable. Look up how to add a python command to Path. You'll get there!

**Comment by iftsv** [comment]
@levfo thanks, the file is here /home/{%user_name%}/.local/bin/auto_subtitle
