### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by Shir8795** [m1guelpf/auto-subtitle#64]
ffmpeg.input(path).output(
    ^^^^^^^^^^^^
AttributeError: module 'ffmpeg' has no attribute 'input'

**Comment by ToP29** [comment]
@Wrty789 Would you mind sharing the solution?

**Comment by NaGUi-code** [comment]
`pip uninstall ffmpeg`
`pip uninstall ffmpeg-python`

And then do 

`pip install ffmpeg-python`

[same problem issue](https://github.com/kkroening/ffmpeg-python/issues/174)
